os: osx

language: generic

env:
  - SWITCH=4.11.0
  - OPAM_VERSION=2.0.7

before_script:
  - set -e
  - wget https://github.com/ocaml/opam/releases/download/$OPAM_VERSION/opam-$OPAM_VERSION-x86_64-macos
  - sudo mv opam-$OPAM_VERSION-x86_64-macos /usr/local/bin/opam
  - sudo chmod a+x /usr/local/bin/opam
  - opam init -y --compiler $SWITCH --disable-sandboxing
  - eval `opam env`
  - ocaml -version

script:
  - opam pin add -y --no-action soupault .
  - opam install -y --destdir . soupault

notifications:
  email:
    recipients:
      - daniil+soupault@baturin.org
    on_success: always
on_failure: always

addons:
  artifacts:
    working_dir: bin
